package Model.Exc4;

import java.util.ArrayList;
import java.util.Scanner;

public class Ferry {
    private int id;
    private String name;
    private int capacity;
    private ArrayList<Vehicle> vehicles;
    private String route;

    public Ferry() {
        this.vehicles= new ArrayList();
        this.id=1;
    }

    public void setId(int id) {
        this.id = id+1;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }

    public void setRoute(String route) {
        this.route = route;
    }

    public String getName() {
        return name;
    }

    public int getCapacity() {
        return capacity;
    }

    public ArrayList<Vehicle> getVehicles() {
        return vehicles;
    }

    public void setVehicle(Vehicle v) {
        this.vehicles.add(v);
    }


    public String getRoute() {
        return route;
    }

    public int counting(){
        return vehicles.size();
    }


    public void requestData() {
        System.out.println("\nEnter the Ferry's name: ");
        Scanner name = new Scanner(System.in);
        String s1Name = name.nextLine();
        System.out.println("\nEnter the Ferry's capacity");
        Scanner size = new Scanner(System.in);
        int s1Size = size.nextInt();
        System.out.println("\nEnter the Ferry's route (country -> country ): ");
        Scanner route = new Scanner(System.in);
        String s1Route = route.nextLine();
        setName(s1Name);
        setCapacity(s1Size);
        setRoute(s1Route);
    }

    /**
     * Collect data to create a new song
     * @return returns a new song type Song
     */
    public Vehicle collectVehicleData(){
        System.out.println("\nEnter the vehicle's type: ");
        Scanner type = new Scanner(System.in);
        String s1Type = type.nextLine();
        System.out.println("\nEnter the vehicle's number passengers:");
        Scanner numberPass = new Scanner(System.in);
        int s1NumberPass = numberPass.nextInt();
        System.out.println("\nThere is crew? (true or false): ");
        Scanner crew = new Scanner(System.in);
        boolean s1Crew = crew.nextBoolean();
        System.out.println("\nEnter the vehicle's number wheels: ");
        Scanner numberWheels = new Scanner(System.in);
        int s1NumberWheels = numberWheels.nextInt();
        System.out.println("\nEnter the vehicle's medium move: ");
        Scanner mediumMove = new Scanner(System.in);
        String s1MediumMove = mediumMove.nextLine();
        int autogeneratedId = getVehicles().size()+1;
        return new Vehicle(autogeneratedId,s1Type,s1NumberPass,s1Crew,s1NumberWheels,s1MediumMove);
    }

    public void showInformation() {
        System.out.println("\n++++++++++++++ Ferry: " + this.id +" ++++++++++++++" + "\n\tName: " + this.name + "\n\tCapacity: " + capacity +
                " Vehicles\n\tRoute: " + route);
        if(vehicles.size() > 0){
            System.out.println("\tVehicles: ");
            for (Vehicle j: getVehicles()) {
                System.out.println("\n\tId Vehicle: " + j.getId() + "\n\t\tType: " + j.getType() +
                        "\n\t\tRegistration Date: " + j.getRegistrationDate().getTime() +
                        "\n\t\tMedium Move: " + j.getMediumMove());
            }
        }else{
            System.out.println("\tVehicles: none");
        }
        System.out.print("-----------------------------------------\n\n");
    }




}
